build: false
environment:
  matrix:
    - PYTHON: "C:/Python27"
      FFMPEG: "release"
    - PYTHON: "C:/Python34"
      FFMPEG: "release"
    - PYTHON: "C:/Python35"
      FFMPEG: "release"
    - PYTHON: "C:/Python36"
      FFMPEG: "release"
    - PYTHON: "C:/Python36"
      FFMPEG: "release"
matrix:
  allow_failures:
    - FFMPEG: "git"
init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
install:
  - "%PYTHON%/python.exe -m pip install wheel"
  - "%PYTHON%/python.exe -m pip install -e ."
  # Install ffmpeg
  - ps: Start-FileDownload ('https://www.gyan.dev/ffmpeg/builds/ffmpeg-' + $env:FFMPEG + '-full.7z') ffmpeg-full.7z
  - 7z x ffmpeg-full.7z > NULL
  - "for /F %%x in ('dir /b ffmpeg-*-full_build') do SET PATH=%cd%\\%%x\\bin;%PATH%"
  # check ffmpeg installation (also shows version)
  - "ffmpeg.exe -version"
test_script:
  - "%PYTHON%/python.exe test/test.py"
